// 'use client';

import { Geist, Geist_Mono } from "next/font/google";

import 'shared/styles/globals.css';
import FontProvider from 'shared/components/FontProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Try to load font from localStorage if it exists (Runs on server)
  const fontFamily = typeof window !== "undefined" ? localStorage.getItem("fontFamily") || "Roboto" : "Roboto";
  return (
    <html lang="en">
      <head>
        {/* Set font-family before hydration to prevent FOUC */}
        <style>{`:root { --font-family: ${fontFamily}; }`}</style>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <FontProvider /> {/* ✅ This is the only Client Component */}
        {children}
      </body>
    </html>
  );
}
